name: Generate snake animation

on:
  schedule:
    - cron: "0 */6 * * *"  # every 12 hours
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: DINESHKUMAR-K-16
          outputs: |
            dist/snake.svg

      - name: Push the file to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
